#!/usr/bin/env python
# coding=utf-8

BASE_URL = 'http://202.199.96.30/'
LOGIN_METHOD = 'ACTIONLOGON.APPPROCESS?mode=4'
CAPTCHA_METHOD = 'ACTIONVALIDATERANDOMPICTURE.APPPROCESS'
CLASS_METHOD = 'ACTIONQUERYCLASSSTUDENT.APPPROCESS?mode=2&query=1'
RESULT_METHOD = 'ACTIONQUERYSTUDENTSCOREBYSTUDENTNO.APPPROCESS?mode=2'

#  Headers
USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
HEADERS = {
        'User-Agent': USER_AGENT,
        'Referer': BASE_URL,
        }
CLASS_ID = ['学号', '姓名', '性别']

